"""
Mecanum 4WD Robot — Remote Control Program
============================================
Novapi-based X-type mecanum wheel chassis remote control.
  Left stick  → omnidirectional movement
  Right stick → in-place rotation
  Both sticks can be used simultaneously (e.g. strafe + rotate).

Hardware:
  Chassis — Encoder motor x4 (X-type mecanum layout)
    - M1 (front-left)  — normal wiring
    - M2 (front-right) — reversed wiring
    - M3 (rear-left)   — normal wiring
    - M4 (rear-right)  — reversed wiring
  Actuators —
    - DC1/DC2/DC3 — DC motors (ball collector), power expand board
    - M5 — Encoder motor (ball roller)
    - BL1/BL2 — Brushless motors, power expand board
    - SV1/SV2 — Smart servos, M6 port chain (INDEX1/INDEX2)

Controls:
  Left stick  ↑↓  = forward/back (指数曲线, 低速细腻)
  Left stick  ←→  = strafe left/right
  Right stick ←→  = rotate left/right (独立曲线指数)
  N1          — both servos fire (BL must be on first)
  N2          — M5=-100 + DC2=+100
  N4          — M5=+100 + DC2=-100
  N3          — unused
  D-pad ↑↓   — BL speed ±5 (range 10~100)
  D-pad ←     — DC3 oscillate -100↔+100 toggle
  D-pad →     — unused
  R2          — BL1+BL2 both on/off
  L1          — face flip toggle (swap front/back)
  L2          — unused
  R1          — unused
  Menu (≡)    — debug mode toggle
  +           — start auto program (AUTO_SEQUENCE)

X-type Mecanum Kinematics:
            Forward (+Vy)
                ^
         M1 <--+--> M2    (FL M1, FR M2)
                |
         M3 <--+--> M4    (RL M3, RR M4)

  Standard inverse kinematics (all wheels forward = positive rotation):
    M1_raw =  Vx + Vy + omega
    M2_raw = -Vx + Vy - omega
    M3_raw = -Vx + Vy + omega
    M4_raw =  Vx + Vy - omega

  M2, M4 reversed wiring correction:
    M2_out = -( -Vx + Vy - omega) =  Vx - Vy + omega
    M4_out = -(  Vx + Vy - omega) = -Vx - Vy + omega

  Vector scaling: if any |power| > 100, scale all 4 proportionally.
"""
import novapi
import time
from mbuild import gamepad
from mbuild import power_expand_board
from mbuild.encoder_motor import encoder_motor_class
from mbuild.led_matrix import led_matrix_class

# ---- Smart servo: optional, robot may not have this hardware ----
try:
    from mbuild.smartservo import smartservo_class
    _HAS_SERVO = True
except ImportError:
    _HAS_SERVO = False
    smartservo_class = None

# ==================== Configuration ====================
SPEED_SCALE = 0.7        # 最大功率倍率 (摇杆推满 = 70%)
DEAD_ZONE = 8            # 摇杆死区 (|值| < 8 → 0)
LOOP_DELAY = 0.02        # 主循环间隔 (秒)
JOYSTICK_EXPO = 2.0      # 摇杆指数曲线: 1.0=线性, 2.0=二次, 3.0=三次 (推荐1.5~2.5)
OMEGA_EXPO = 2.0         # 旋转摇杆独立曲线指数 (通常与平移一致, 可单独调)

INVERT_VX = False
INVERT_VY = True
INVERT_OMEGA = True

# DC collector motors
DC_COLLECTOR_PORT1 = "DC1"
DC_COLLECTOR_PORT2 = "DC2"
DC_COLLECTOR_PORT3 = "DC3"
DC_COLLECTOR_SPEED = 100

# M5 roller motor
ROLLER_SPEED = 80

# Servo fire action (L1=SV1, R1=SV2)
BL_ACTION_SPEED = 80
BL_SPINUP_DELAY = 0.1
SERVO1_ACTION_ANGLE = -40
SERVO2_ACTION_ANGLE = 40
SERVO_ACTION_SPEED = 50
SERVO_RETURN_DELAY = 0.14

# 8x16 LED matrix (landscape: 16col x 8row)
LED_PORT = "PORT2"
LED_INDEX = "INDEX1"

# Debug mode
DEBUG_TEST_SPEED = 50
DEBUG_SERVO_ANGLE = 90
SERVO_MOVE_SPEED = 30
DEBUG_MOTOR_TYPES = ["Motor", "DC", "BLDC", "Servo"]
DEBUG_MOTOR_NAMES = ["M1", "M2", "M3", "M4", "M5"]
DEBUG_DC_NAMES = ["DC1", "DC2"]
DEBUG_BLDC_NAMES = ["BL1", "BL2"]
DEBUG_SERVO_NAMES = ["SV1", "SV2"]
DEBUG_ALL_NAMES = [DEBUG_MOTOR_NAMES, DEBUG_DC_NAMES, DEBUG_BLDC_NAMES, DEBUG_SERVO_NAMES]

# ==================== Auto Program ====================
AUTO_SPEED = 50
AUTO_STEP_DELAY = 0.02
AUTO_RAMP_MS = 100
AUTO_ACCEL_MS = 250             # ms: within-step 0→100→0 acceleration ramp

# ==================== Debug Calibration ====================
DEBUG_CAL_POWER    = 50    # forward power % for encoder calibration in debug mode
DEBUG_CAL_DURATION = 1.0   # seconds to drive during calibration
DEBUG_CAL_ACCEL_MS = 250   # ms ramp-up/down (same shape as AUTO_ACCEL_MS)
AUTO_SEQUENCE = [
    # === Auto-generated by trajectory_planner on 2026-07-05 18:04 ===
    # Source: (unsaved)  |  Format: v5-encoder
    # Mode: translation | speed: 100.0 cm/s | power: 85
    ('enc_move', 90, 44, 0),
    ('enc_move', 716, 79, 0),
    ('enc_move', 265, 36, 0),
    ('enc_move', 270, 9, 0),
    ('enc_move', 90, 2, 0),
    ('enc_move', 90, -4, 0),
    ('enc_move', 180, 0, 0),
    ('enc_move', 90, 4, 0),
    ('enc_move', 180, 0, 0),
    ('dc_motor', 'DC1', -100),
    ('dc_motor', 'DC2', -100),
    ( 0.13,  -25,    2,  -50),
    ( 0.27,  -25,    2,   50),
    ( 0.27,  -25,    2,  -50),
    ( 0.27,  -25,    2,   50),
    ( 0.27,  -25,    2,  -50),
    ( 0.27,  -25,    2,   50),
    ( 0.27,  -25,    2,  -50),
    ( 0.27,  -25,    2,   50),
    ( 0.13,  -25,    2,  -50),
    ( 0.10,    0,    0,    0),
    ('dc_motor', 'DC1', 0),
    ('dc_motor', 'DC2', 0),
    ('enc_move', 90, 3, 0),
    ('enc_move', 90, 10, 0),
    ('enc_move', 269, 25, 0),
    ('enc_move', 86, 57, 0),
    ('enc_move', 447, 84, 0),
    ('enc_move', 90, 58, 0),
    ('enc_move', 34, 32, 0),
    ('enc_stop', 0, 0, 0),
    ('spin', 90, 40),
    ('enc_stop', 0, 0, 0),
]

# ==================== Hardware Init ====================
__motor_M1 = encoder_motor_class("M1", "INDEX1")
__motor_M2 = encoder_motor_class("M2", "INDEX1")
__motor_M3 = encoder_motor_class("M3", "INDEX1")
__motor_M4 = encoder_motor_class("M4", "INDEX1")
__motor_M5 = encoder_motor_class("M5", "INDEX1")
__led = led_matrix_class(LED_PORT, LED_INDEX)

if _HAS_SERVO:
    try:
        __servo_1 = smartservo_class("M6", "INDEX1")
        __servo_2 = smartservo_class("M6", "INDEX2")
    except Exception:
        _HAS_SERVO = False

# ==================== Kinematics ====================
def mecanum_kinematics(Vx, Vy, omega):
    M1 =  Vx + Vy + omega
    M2 = -Vx + Vy - omega
    M3 = -Vx + Vy + omega
    M4 =  Vx + Vy - omega

    M2 = -M2
    M4 = -M4

    max_abs = max(abs(M1), abs(M2), abs(M3), abs(M4))
    if max_abs > 100:
        scale = 100.0 / max_abs
        M1 *= scale
        M2 *= scale
        M3 *= scale
        M4 *= scale

    return M1, M2, M3, M4


def apply_dead_zone(value, threshold=DEAD_ZONE):
    if abs(value) < threshold:
        return 0
    return value


def apply_response_curve(value, exponent=JOYSTICK_EXPO, max_input=100.0):
    """WPILib 风格的指数响应曲线。

    output = sign(value) * (|value| / max_input)^exponent * max_input

    示例 (exponent=2.0, max_input=100):
      摇杆 25% → 6.25%  (极细腻)
      摇杆 50% → 25%    (柔和)
      摇杆 75% → 56.25%
      摇杆 100% → 100%  (满功率)
    """
    if value == 0:
        return 0.0
    sign = 1.0 if value > 0 else -1.0
    normalized = abs(value) / max_input
    curved = normalized ** exponent
    return sign * curved * max_input


def stop_all_motors():
    __motor_M1.set_power(0)
    __motor_M2.set_power(0)
    __motor_M3.set_power(0)
    __motor_M4.set_power(0)
    __motor_M5.set_power(0)
    power_expand_board.set_power(DC_COLLECTOR_PORT1, 0)
    power_expand_board.set_power(DC_COLLECTOR_PORT2, 0)
    power_expand_board.set_power(DC_COLLECTOR_PORT3, 0)
    power_expand_board.stop("BL1")
    power_expand_board.stop("BL2")
    if _HAS_SERVO:
        try:
            __servo_1.set_power(0)
            __servo_2.set_power(0)
        except Exception:
            pass


def debug_stop_motor():
    if debug_motor_type == 0:
        motor = [__motor_M1, __motor_M2, __motor_M3, __motor_M4, __motor_M5][debug_motor_index]
        motor.set_power(0)
    elif debug_motor_type == 1:
        port = [DC_COLLECTOR_PORT1, DC_COLLECTOR_PORT2][debug_motor_index]
        power_expand_board.set_power(port, 0)
    elif debug_motor_type == 2:
        port = ["BL1", "BL2"][debug_motor_index]
        power_expand_board.stop(port)
    else:
        if _HAS_SERVO:
            try:
                servo = [__servo_1, __servo_2][debug_motor_index]
                servo.set_power(0)
            except Exception:
                pass


# ==================== State ====================
# Normal mode
bl1_on = False
bl2_on = False
face_flipped = False          # L1: 面翻转（正面↔反面）

# Encoder calibration deltas (filled after debug-mode + key calibration)
_cal_delta_M1 = None      # encoder delta for M1 after calibration
_cal_delta_M2 = None      # encoder delta for M2
_cal_delta_M3 = None      # encoder delta for M3
_cal_delta_M4 = None      # encoder delta for M4
_enc_cal_start = [0, 0, 0, 0]  # encoder start values snapshot

# Auto-mode encoder calibration state (global, NOT object attributes — MicroPython safe)
_enc_cal_auto_started = False       # True = first tick already done
_enc_cal_M1_start = 0               # M1 start count snapshot
_enc_cal_M2_start = 0               # M2 start count snapshot
_enc_cal_M3_start = 0               # M3 start count snapshot
_enc_cal_M4_start = 0               # M4 start count snapshot

# Set to True after calibration so N1-N4 show deltas
_debug_cal_done = False

# Auto program
auto_mode = False
auto_step = 0
auto_step_start = 0.0
auto_prev_Vx = 0.0
auto_prev_Vy = 0.0
auto_prev_omega = 0.0

# Servo fire sequence (L1=SV1, R1=SV2)
sv1_phase = 0
sv1_time = 0.0
sv2_phase = 0
sv2_time = 0.0

# M5 roller motor
m5_speed = 0
n2_on = False                # N2 切换状态
n4_on = False                # N4 切换状态
dc3_osc = False              # N3: DC3 振荡模式开关
dc3_osc_dir = 1               # N3: DC3 振荡当前方向 1=正 -1=负
dc3_osc_timer = 0.0           # N3: DC3 振荡上次翻转时刻
_dpad_lr_conflict = 0          # D-pad 左右冲突连续计数
_dpad_ud_conflict = 0          # D-pad 上下冲突连续计数

# Debug mode
debug_mode = False
debug_motor_type = 0
debug_motor_index = 0
debug_show_speed_until = 0.0
debug_show_ok = False
servo_moved = False
servo_dir = 1

# Edge detection (normal mode)
last_N1 = False
last_N2 = False
last_N3 = False
last_N4 = False
last_Plus = False
last_Menu = False
last_L1 = False
last_R1 = False
last_L2 = False
last_R2 = False
last_Dpad_Up = False
last_Dpad_Down = False
last_Dpad_Left = False
last_Dpad_Right = False

# Edge detection (debug mode)
last_Up = False
last_Down = False
last_Left = False
last_Right = False

# ==================== 编码器闭环参数（基于 novapi get_value("angle") 角度制）====================
# novapi 编码电机使用 get_value("angle") 返回角度（度），没有 get_count()！
# ENCODER_TICKS_PER_CM: GUI 端标定常数（ticks/cm），机器人端用于 ticks→cm 换算
ENCODER_TICKS_PER_CM = 18.0000
# 轮子周长 → 角度换算：1 cm = 360° / 轮周长 ≈ 11.459°/cm
_WHEEL_CIRCUMFERENCE_CM = 31.4159  # π × 10cm
_DEG_PER_CM = 360.0 / _WHEEL_CIRCUMFERENCE_CM
# ticks → 度 换算因子
_TICKS_TO_DEG = _DEG_PER_CM / ENCODER_TICKS_PER_CM
# 到位死区（度）：电机角度误差小于此值视为到达
PROFILE_DEADBAND_DEG = 8
# 每步最大等待时间（秒），防止卡死
_ENC_STEP_TIMEOUT = 8.0
# 功率 → rpm 映射：move(deg, rpm) 的速度参数
# power=85 → 680rpm（电机物理解限约200-250rpm，设高确保不成为瓶颈）
_RPM_PER_POWER = 8.0

# 编码器闭环状态（简化：用 novapi 内置 move() 替代自定义 PID）
_enc_targets = [0, 0, 0, 0]        # M1-M4 目标角度（绝对角度，度）
_enc_step_initialized = -1           # 已初始化的 auto_step 索引
_enc_step_start_time = 0.0           # 当前步开始时刻

# ==================== 编码器闭环函数（基于 novapi move() + get_value("angle")）====================
# novapi 编码电机有内置位置闭环 move(degrees, rpm)，无需自己写 PID！
# get_value("angle") 返回当前角度（度），move() 是非阻塞的相对角度转动。

_motors = None  # 延迟初始化，在第一次调用时赋值

def _get_motors():
    """返回四轮电机列表（延迟初始化，避免模块加载顺序问题）"""
    global _motors
    if _motors is None:
        _motors = [__motor_M1, __motor_M2, __motor_M3, __motor_M4]
    return _motors


def _enc_move_start(total_ticks, vy_power):
    """初始化编码器直走：计算目标角度 → 调用 novapi move()

    total_ticks: GUI 导出的 ticks 值（ticks = cm × ENCODER_TICKS_PER_CM）
    vy_power:   前进功率百分比（用于确定方向和速度）
    """
    global _enc_targets, _enc_step_start_time

    motors = _get_motors()

    # ticks → cm → 度
    distance_cm = abs(total_ticks) / ENCODER_TICKS_PER_CM
    total_degrees = distance_cm * _DEG_PER_CM  # 每个轮子转动的角度

    # 运动方向由 total_ticks 符号决定（正=前进，负=后退）
    direction = 1 if total_ticks >= 0 else -1

    # 用运动学计算各轮方向
    vy_dir = abs(vy_power) * direction  # 带方向的 Vy 功率
    M1p, M2p, M3p, M4p = mecanum_kinematics(0, vy_dir, 0)
    signs = [1 if M1p >= 0 else -1, 1 if M2p >= 0 else -1,
             1 if M3p >= 0 else -1, 1 if M4p >= 0 else -1]

    # 记录起始位置 → 计算目标绝对角度
    starts = [m.get_value("angle") for m in motors]
    _enc_targets = [int(starts[i] + signs[i] * total_degrees) for i in range(4)]

    # 速度：功率% → rpm
    motor_rpm = max(30, int(abs(vy_power) * _RPM_PER_POWER))

    # 调用 novapi 内置位置闭环：非阻塞，电机会自动停到目标
    for i in range(4):
        try:
            motors[i].move(int(signs[i] * total_degrees), motor_rpm)
        except Exception:
            pass

    _enc_step_start_time = novapi.timer()
    print(">>> enc_move: %.1fcm (%d°) @%drpm  dir=%d" %
          (distance_cm, int(total_degrees), motor_rpm, direction))


def _enc_move_tick(max_power, stop_motors=True):
    """编码器直走单步检测 → 返回 True=已到达目标

    novapi 的 move() 会自动减速停在目标角度，这里只需检查是否到位。
    加入超时保护防止卡死。

    v5.1: stop_motors=False 时到达目标不刹停，用于连续 enc_move 衔接。
    """
    motors = _get_motors()

    # 超时保护
    if novapi.timer() - _enc_step_start_time > _ENC_STEP_TIMEOUT:
        if stop_motors:
            for m in motors:
                m.set_power(0)
        print(">>> enc_move: 超时，强制进入下一步")
        return True

    # 检查四轮是否到位
    all_done = True
    for i in range(4):
        try:
            cur = motors[i].get_value("angle")
            if abs(_enc_targets[i] - cur) > PROFILE_DEADBAND_DEG:
                all_done = False
                break
        except Exception:
            pass

    if all_done:
        if stop_motors:
            for m in motors:
                m.set_power(0)
        return True

    return False


def _enc_rot_start(total_ticks, omega_power):
    """初始化编码器自旋：计算目标角度 → 调用 novapi move()"""
    global _enc_targets, _enc_step_start_time

    motors = _get_motors()

    # ticks → 旋转角度（度）
    # 自旋时 ticks 代表旋转编码量，直接换算为角度
    distance_cm = abs(total_ticks) / ENCODER_TICKS_PER_CM
    total_degrees = distance_cm * _DEG_PER_CM

    direction = 1 if total_ticks >= 0 else -1

    # 自旋运动学
    w_dir = abs(omega_power) * direction
    M1p, M2p, M3p, M4p = mecanum_kinematics(0, 0, w_dir)
    signs = [1 if M1p >= 0 else -1, 1 if M2p >= 0 else -1,
             1 if M3p >= 0 else -1, 1 if M4p >= 0 else -1]

    starts = [m.get_value("angle") for m in motors]
    _enc_targets = [int(starts[i] + signs[i] * total_degrees) for i in range(4)]

    motor_rpm = max(30, int(abs(omega_power) * _RPM_PER_POWER))

    for i in range(4):
        try:
            motors[i].move(int(signs[i] * total_degrees), motor_rpm)
        except Exception:
            pass

    _enc_step_start_time = novapi.timer()
    print(">>> enc_rot: %.1f° @%drpm" % (total_degrees, motor_rpm))


def _enc_rot_tick(max_power, stop_motors=True):
    """编码器自旋单步检测 → 返回 True=已到达目标（v5.1: 支持连续衔接）"""
    return _enc_move_tick(max_power, stop_motors=stop_motors)


# ==================== Startup ====================

__led.show("Main")
novapi.reset_timer()

# ==================== Main Loop ====================
while True:
    # ================================================================
    #  Auto Mode
    # ================================================================
    if auto_mode:
        elapsed = novapi.timer() - auto_step_start
        step = AUTO_SEQUENCE[auto_step]

        # ---- Tagged command tuple (first element is a string) ----
        if isinstance(step[0], str):
            tag = step[0]

            if tag == "servo":
                _, sv_id, angle, speed, wait_ms = step
                if elapsed < AUTO_STEP_DELAY * 1.5:
                    if _HAS_SERVO:
                        try:
                            sv = __servo_1 if sv_id in ("S1", "SV1") else __servo_2
                            sv.move_to(angle, speed)
                        except Exception:
                            pass
                if elapsed * 1000.0 >= wait_ms:
                    auto_step += 1
                    if auto_step >= len(AUTO_SEQUENCE):
                        auto_mode = False
                        auto_step = 0
                    else:
                        auto_step_start = novapi.timer()

            elif tag == "delay":
                dur = step[1]
                if elapsed >= dur:
                    auto_step += 1
                    if auto_step >= len(AUTO_SEQUENCE):
                        auto_mode = False
                        auto_step = 0
                    else:
                        auto_step_start = novapi.timer()

            elif tag == "motor":
                # 设置编码电机持续转动（立即执行，不等待）
                _, motor_id, power = step
                motor_map = {"M1": __motor_M1, "M2": __motor_M2, "M3": __motor_M3,
                             "M4": __motor_M4, "M5": __motor_M5}
                m = motor_map.get(str(motor_id))
                if m is not None:
                    m.set_power(int(power))
                    print(">>> motor %s → %d%%" % (motor_id, power))
                auto_step += 1
                if auto_step >= len(AUTO_SEQUENCE):
                    auto_mode = False
                    auto_step = 0
                else:
                    auto_step_start = novapi.timer()

            elif tag == "dc_motor":
                # 设置直流电机持续转动（立即执行，不等待）
                _, dc_port, power = step
                port = str(dc_port)
                power_expand_board.set_power(port, int(power))
                print(">>> dc_motor %s → %d%%" % (port, power))
                auto_step += 1
                if auto_step >= len(AUTO_SEQUENCE):
                    auto_mode = False
                    auto_step = 0
                else:
                    auto_step_start = novapi.timer()

            elif tag == "enc_move":
                # v5.1 编码器闭环直走：使用 novapi 内置 move() 位置控制
                # 修复"一格一格走"：当下一步也是 enc_move 时，不刹停，直接衔接
                _, total_ticks, vy_power, _w = step
                if _enc_step_initialized != auto_step:
                    _enc_move_start(total_ticks, vy_power)
                    _enc_step_initialized = auto_step

                # 预判下一步：如果是连续同向 enc_move，提前衔接避免停顿
                next_step = AUTO_SEQUENCE[auto_step + 1] if auto_step + 1 < len(AUTO_SEQUENCE) else None
                next_is_enc_move = (next_step is not None
                                    and isinstance(next_step[0], str)
                                    and next_step[0] == 'enc_move')

                if _enc_move_tick(abs(vy_power), stop_motors=(not next_is_enc_move)):
                    auto_step += 1
                    if auto_step >= len(AUTO_SEQUENCE):
                        auto_mode = False; auto_step = 0
                        stop_all_motors()
                    else:
                        auto_step_start = novapi.timer()

            elif tag == "enc_rot":
                # v5.1 编码器闭环自旋：使用 novapi 内置 move() 位置控制
                # 修复"一格一格走"：当下一步也是 enc_rot 时，不刹停，直接衔接
                _, total_ticks, _vy, omega_power = step
                if _enc_step_initialized != auto_step:
                    _enc_rot_start(total_ticks, omega_power)
                    _enc_step_initialized = auto_step

                next_step = AUTO_SEQUENCE[auto_step + 1] if auto_step + 1 < len(AUTO_SEQUENCE) else None
                next_is_enc_rot = (next_step is not None
                                   and isinstance(next_step[0], str)
                                   and next_step[0] == 'enc_rot')

                if _enc_rot_tick(abs(omega_power), stop_motors=(not next_is_enc_rot)):
                    auto_step += 1
                    if auto_step >= len(AUTO_SEQUENCE):
                        auto_mode = False; auto_step = 0
                        stop_all_motors()
                    else:
                        auto_step_start = novapi.timer()

            elif tag == "enc_stop":
                # v5 停止缓冲：短暂停顿后进入下一步（不终止整个序列）
                stop_all_motors()
                auto_step += 1
                if auto_step >= len(AUTO_SEQUENCE):
                    auto_mode = False
                    auto_step = 0
                    print(">>> 编码器序列完成")
                else:
                    auto_step_start = novapi.timer()
                    print(">>> enc_stop → 步骤 %d/%d" % (auto_step + 1, len(AUTO_SEQUENCE)))

            elif tag == "encoder_cal":
                # Encoder calibration from GUI: record angles → drive → compute deltas
                _, cal_dur, cal_Vx, cal_Vy, cal_omega = step  # 5-tuple
                if not _enc_cal_auto_started:
                    # First tick: snapshot start encoder angles
                    _enc_cal_M1_start = __motor_M1.get_value("angle")
                    _enc_cal_M2_start = __motor_M2.get_value("angle")
                    _enc_cal_M3_start = __motor_M3.get_value("angle")
                    _enc_cal_M4_start = __motor_M4.get_value("angle")
                    auto_step_start = novapi.timer()
                    _enc_cal_auto_started = True
                    __led.show("CAL")
                    print(">>> 编码器标定开始（GUI）！初始角度 M1=%d M2=%d M3=%d M4=%d" %
                          (_enc_cal_M1_start, _enc_cal_M2_start,
                           _enc_cal_M3_start, _enc_cal_M4_start))

                if elapsed >= cal_dur:
                    # Calibration complete: record end angles
                    M1_end = __motor_M1.get_value("angle")
                    M2_end = __motor_M2.get_value("angle")
                    M3_end = __motor_M3.get_value("angle")
                    M4_end = __motor_M4.get_value("angle")
                    _cal_delta_M1 = M1_end - _enc_cal_M1_start
                    _cal_delta_M2 = M2_end - _enc_cal_M2_start
                    _cal_delta_M3 = M3_end - _enc_cal_M3_start
                    _cal_delta_M4 = M4_end - _enc_cal_M4_start
                    _debug_cal_done = True
                    _enc_cal_auto_started = False
                    stop_all_motors()
                    auto_mode = False
                    auto_step = 0
                    __led.show("done")
                    print(">>> 编码器标定完成！增量: M1=%d M2=%d M3=%d M4=%d" %
                          (_cal_delta_M1, _cal_delta_M2, _cal_delta_M3, _cal_delta_M4))
                    print("    按 N1/N2/N3/N4 在 LED 查看各电机增量（E####）")
                else:
                    # Drive forward during calibration
                    _cvx = cal_Vx
                    _cvy = cal_Vy
                    _cw = cal_omega
                    if INVERT_VX:
                        _cvx = -_cvx
                    if INVERT_VY:
                        _cvy = -_cvy
                    if INVERT_OMEGA:
                        _cw = -_cw
                    M1p, M2p, M3p, M4p = mecanum_kinematics(_cvx, _cvy, _cw)
                    __motor_M1.set_power(M1p)
                    __motor_M2.set_power(M2p)
                    __motor_M3.set_power(M3p)
                    __motor_M4.set_power(M4p)

            elif tag == "spin":
                # Spin in place: ("spin", degrees, omega_power)
                _, deg, _w = step
                rot_speed = 90.0 * abs(_w) / 50.0
                need_dur = abs(deg) / max(rot_speed, 1.0)
                if elapsed < AUTO_STEP_DELAY * 1.5:
                    pass
                w_sign = 1 if deg > 0 else -1
                w_out = w_sign * abs(_w)
                _sp = mecanum_kinematics(0, 0, w_out)
                __motor_M1.set_power(_sp[0])
                __motor_M2.set_power(_sp[1])
                __motor_M3.set_power(_sp[2])
                __motor_M4.set_power(_sp[3])
                if elapsed >= need_dur:
                    __motor_M1.set_power(0)
                    __motor_M2.set_power(0)
                    __motor_M3.set_power(0)
                    __motor_M4.set_power(0)
                    auto_step += 1
                    if auto_step >= len(AUTO_SEQUENCE):
                        auto_mode = False
                        auto_step = 0
                    else:
                        auto_step_start = novapi.timer()

            else:
                # Unknown tag: skip
                auto_step += 1
                auto_step_start = novapi.timer()

            time.sleep(AUTO_STEP_DELAY)
            continue

        # ---- Standard 4-tuple motion step ----
        step_duration, step_Vx, step_Vy, step_omega = step

        if INVERT_VX:
            step_Vx = -step_Vx
        if INVERT_VY:
            step_Vy = -step_Vy
        if INVERT_OMEGA:
            step_omega = -step_omega

        if elapsed >= step_duration:
            auto_prev_Vx = step_Vx
            auto_prev_Vy = step_Vy
            auto_prev_omega = step_omega
            auto_step += 1
            if auto_step >= len(AUTO_SEQUENCE):
                stop_all_motors()
                auto_mode = False
                auto_step = 0
                auto_prev_Vx = 0.0
                auto_prev_Vy = 0.0
                auto_prev_omega = 0.0
            else:
                auto_step_start = novapi.timer()
                nstep = AUTO_SEQUENCE[auto_step]
                if not isinstance(nstep[0], str):
                    nd, nVx, nVy, nw = nstep
        else:
            # Between-step interpolation
            if AUTO_RAMP_MS > 0 and elapsed * 1000.0 < AUTO_RAMP_MS:
                alpha = elapsed * 1000.0 / AUTO_RAMP_MS
                Vx_out = auto_prev_Vx + (step_Vx - auto_prev_Vx) * alpha
                Vy_out = auto_prev_Vy + (step_Vy - auto_prev_Vy) * alpha
                omega_out = auto_prev_omega + (step_omega - auto_prev_omega) * alpha
            else:
                Vx_out = step_Vx
                Vy_out = step_Vy
                omega_out = step_omega

            # Within-step acceleration ramp (0→100→0) to prevent wheel slip
            step_ms = step_duration * 1000.0
            elapsed_ms = elapsed * 1000.0
            if AUTO_ACCEL_MS > 0 and step_ms > AUTO_ACCEL_MS * 2:
                if elapsed_ms < AUTO_ACCEL_MS:
                    # Ramp up: power goes 0 → target
                    accel = elapsed_ms / AUTO_ACCEL_MS
                elif elapsed_ms > step_ms - AUTO_ACCEL_MS:
                    # Ramp down: power goes target → 0
                    accel = (step_ms - elapsed_ms) / AUTO_ACCEL_MS
                else:
                    # Cruise at full power
                    accel = 1.0
            else:
                accel = 1.0

            Vx_out *= accel
            Vy_out *= accel
            omega_out *= accel

            M1p, M2p, M3p, M4p = mecanum_kinematics(Vx_out, Vy_out, omega_out)
            __motor_M1.set_power(M1p)
            __motor_M2.set_power(M2p)
            __motor_M3.set_power(M3p)
            __motor_M4.set_power(M4p)

        time.sleep(AUTO_STEP_DELAY)
        continue

    # ================================================================
    #  Debug Mode
    # ================================================================
    if debug_mode:
        cur_Up = gamepad.is_key_pressed("Up")
        cur_Down = gamepad.is_key_pressed("Down")
        cur_Left = gamepad.is_key_pressed("Left")
        cur_Right = gamepad.is_key_pressed("Right")
        cur_N1 = gamepad.is_key_pressed("N1")
        cur_N2 = gamepad.is_key_pressed("N2")
        cur_N3 = gamepad.is_key_pressed("N3")
        cur_N4 = gamepad.is_key_pressed("N4")
        cur_Plus = gamepad.is_key_pressed("+")
        cur_Menu = gamepad.is_key_pressed("≡")
        cur_R1 = gamepad.is_key_pressed("R1")
        cur_L1 = gamepad.is_key_pressed("L1")

        # ≡ key: exit debug mode
        if cur_Menu and not last_Menu:
            debug_stop_motor()
            debug_mode = False
            stop_all_motors()
            __led.show("Main")
            last_Up = last_Down = last_Left = last_Right = False
            last_N1 = last_N2 = last_N3 = last_N4 = False
            last_Menu = cur_Menu
            debug_show_ok = False
            time.sleep(0.3)
            continue

        # ----------------------------------------------------------------
        #  + key: encoder calibration / auto sequence
        #    If AUTO_SEQUENCE has a tagged step → start auto sequence
        #    Otherwise → built-in blocking calibration
        # ----------------------------------------------------------------
        if cur_Plus and not last_Plus:
            last_Plus = cur_Plus

            # Check if GUI exported a calibration / auto sequence
            if len(AUTO_SEQUENCE) > 0 and isinstance(AUTO_SEQUENCE[0][0], str):
                # Start auto sequence (exits debug mode)
                debug_stop_motor()
                debug_mode = False
                stop_all_motors()
                _debug_cal_done = False
                _enc_cal_auto_started = False
                _enc_step_initialized = -1
                _cal_delta_M1 = _cal_delta_M2 = _cal_delta_M3 = _cal_delta_M4 = None
                auto_mode = True
                auto_step = 0
                auto_step_start = novapi.timer()
                auto_prev_Vx = 0.0
                auto_prev_Vy = 0.0
                auto_prev_omega = 0.0
                tag0 = AUTO_SEQUENCE[0][0]
                print(">>> 自动程序启动（从调试模式）！步骤 1/%d: %s" %
                      (len(AUTO_SEQUENCE), tag0))
                __led.show("auto")
                last_Up = last_Down = last_Left = last_Right = False
                last_N1 = last_N2 = last_N3 = last_N4 = False
                last_Menu = cur_Menu
                time.sleep(0.3)
                continue

            # --- Built-in calibration (blocking inner loop) ---
            _enc_cal_start[:] = [
                __motor_M1.get_value("angle"),
                __motor_M2.get_value("angle"),
                __motor_M3.get_value("angle"),
                __motor_M4.get_value("angle"),
            ]
            __led.show("Cal")
            novapi.reset_timer()
            # --- drive loop ---
            while True:
                cal_elapsed = novapi.timer()
                cal_dur_ms = DEBUG_CAL_DURATION * 1000.0
                cal_elapsed_ms = cal_elapsed * 1000.0
                # 0 → full → 0 ramp
                if DEBUG_CAL_ACCEL_MS > 0 and cal_dur_ms > DEBUG_CAL_ACCEL_MS * 2:
                    if cal_elapsed_ms < DEBUG_CAL_ACCEL_MS:
                        accel = cal_elapsed_ms / DEBUG_CAL_ACCEL_MS
                    elif cal_elapsed_ms > cal_dur_ms - DEBUG_CAL_ACCEL_MS:
                        accel = (cal_dur_ms - cal_elapsed_ms) / DEBUG_CAL_ACCEL_MS
                    else:
                        accel = 1.0
                else:
                    accel = 1.0
                cal_vy = DEBUG_CAL_POWER
                if INVERT_VY:
                    cal_vy = -cal_vy
                cal_vy = cal_vy * accel
                M1p, M2p, M3p, M4p = mecanum_kinematics(0, cal_vy, 0)
                __motor_M1.set_power(M1p)
                __motor_M2.set_power(M2p)
                __motor_M3.set_power(M3p)
                __motor_M4.set_power(M4p)
                time.sleep(LOOP_DELAY)
                if cal_elapsed >= DEBUG_CAL_DURATION:
                    break
            # --- stop and record ---
            __motor_M1.set_power(0)
            __motor_M2.set_power(0)
            __motor_M3.set_power(0)
            __motor_M4.set_power(0)
            _enc_end = [
                __motor_M1.get_value("angle"),
                __motor_M2.get_value("angle"),
                __motor_M3.get_value("angle"),
                __motor_M4.get_value("angle"),
            ]
            _cal_delta_M1 = _enc_end[0] - _enc_cal_start[0]
            _cal_delta_M2 = _enc_end[1] - _enc_cal_start[1]
            _cal_delta_M3 = _enc_end[2] - _enc_cal_start[2]
            _cal_delta_M4 = _enc_end[3] - _enc_cal_start[3]
            _debug_cal_done = True
            # Show M1 delta right away; N1-N4 can recall each motor below
            __led.show("E%d" % _cal_delta_M1)
            time.sleep(0.5)
            continue

        last_Plus = cur_Plus

        # ----------------------------------------------------------------
        #  After calibration: N1/N2/N3/N4 show each motor's delta
        # ----------------------------------------------------------------
        if _debug_cal_done:
            if cur_N1 and not last_N1:
                __led.show("E%d" % _cal_delta_M1)
            if cur_N2 and not last_N2:
                __led.show("E%d" % _cal_delta_M2)
            if cur_N3 and not last_N3:
                __led.show("E%d" % _cal_delta_M3)
            if cur_N4 and not last_N4:
                __led.show("E%d" % _cal_delta_M4)

        # D-pad ↑/↓: switch motor type
        if cur_Up and not last_Up:
            debug_motor_type = (debug_motor_type + 1) % len(DEBUG_MOTOR_TYPES)
            max_idx = len(DEBUG_ALL_NAMES[debug_motor_type]) - 1
            if debug_motor_index > max_idx:
                debug_motor_index = 0
            name = DEBUG_ALL_NAMES[debug_motor_type][debug_motor_index]
            __led.show(name)
        if cur_Down and not last_Down:
            debug_motor_type = (debug_motor_type - 1) % len(DEBUG_MOTOR_TYPES)
            max_idx = len(DEBUG_ALL_NAMES[debug_motor_type]) - 1
            if debug_motor_index > max_idx:
                debug_motor_index = 0
            name = DEBUG_ALL_NAMES[debug_motor_type][debug_motor_index]
            __led.show(name)

        # D-pad ←/→: switch motor index
        max_idx = len(DEBUG_ALL_NAMES[debug_motor_type]) - 1
        if cur_Left and not last_Left:
            debug_motor_index = (debug_motor_index - 1) % (max_idx + 1)
            name = DEBUG_ALL_NAMES[debug_motor_type][debug_motor_index]
            __led.show(name)
        if cur_Right and not last_Right:
            debug_motor_index = (debug_motor_index + 1) % (max_idx + 1)
            name = DEBUG_ALL_NAMES[debug_motor_type][debug_motor_index]
            __led.show(name)

        # Idle display
        if not cur_N1 and not cur_N4:
            if debug_show_ok:
                if novapi.timer() >= debug_show_speed_until:
                    debug_show_ok = False
            elif debug_show_speed_until > 0 and novapi.timer() < debug_show_speed_until:
                if debug_motor_type == 3:
                    __led.show("A%d" % DEBUG_SERVO_ANGLE)
                else:
                    __led.show("S%d" % DEBUG_TEST_SPEED)
            else:
                __led.show(DEBUG_ALL_NAMES[debug_motor_type][debug_motor_index])

        # N1/N4: motor test
        servo_moved = False
        if debug_motor_type == 3:
            servo_moved = True
            if _HAS_SERVO:
                try:
                    _sv = [__servo_1, __servo_2][debug_motor_index]
                except Exception:
                    _sv = None
                if cur_N1 and not last_N1 and _sv:
                    _sv.move_to(servo_dir * DEBUG_SERVO_ANGLE, SERVO_MOVE_SPEED)
                elif cur_N4 and not last_N4 and _sv:
                    _sv.move_to(0, SERVO_MOVE_SPEED)
            speed = 0
        else:
            if cur_N1:
                speed = DEBUG_TEST_SPEED
            elif cur_N4:
                if debug_motor_type == 2:
                    speed = 0
                else:
                    speed = -DEBUG_TEST_SPEED
            else:
                speed = 0

        # N2/N3: adjust speed/angle
        if cur_N2 and not last_N2:
            if debug_motor_type == 3:
                DEBUG_SERVO_ANGLE = min(360, DEBUG_SERVO_ANGLE + 5)
                debug_show_speed_until = novapi.timer() + 2.0
            else:
                DEBUG_TEST_SPEED = min(100, DEBUG_TEST_SPEED + 10)
                debug_show_speed_until = novapi.timer() + 2.0
        if cur_N3 and not last_N3:
            if debug_motor_type == 3:
                DEBUG_SERVO_ANGLE = max(0, DEBUG_SERVO_ANGLE - 5)
                debug_show_speed_until = novapi.timer() + 2.0
            else:
                DEBUG_TEST_SPEED = max(0, DEBUG_TEST_SPEED - 10)
                debug_show_speed_until = novapi.timer() + 2.0

        # R1: set servo zero
        if debug_motor_type == 3 and cur_R1 and not last_R1 and _HAS_SERVO:
            try:
                _sv = [__servo_1, __servo_2][debug_motor_index]
                _sv.set_zero()
                __led.show("OK")
                debug_show_speed_until = novapi.timer() + 1.0
                debug_show_ok = True
                servo_moved = True
            except Exception:
                pass

        # L1: toggle servo direction
        if debug_motor_type == 3 and cur_L1 and not last_L1:
            servo_dir = -servo_dir

        # Output
        if debug_motor_type == 0:
            motor = [__motor_M1, __motor_M2, __motor_M3, __motor_M4, __motor_M5][debug_motor_index]
            motor.set_power(speed)
        elif debug_motor_type == 1:
            port = [DC_COLLECTOR_PORT1, DC_COLLECTOR_PORT2][debug_motor_index]
            power_expand_board.set_power(port, speed)
        elif debug_motor_type == 2:
            port = ["BL1", "BL2"][debug_motor_index]
            power_expand_board.set_power(port, speed)
        # type 3 (servo) handled above via move_to, skip set_power

        last_Up = cur_Up
        last_Down = cur_Down
        last_Left = cur_Left
        last_Right = cur_Right
        last_N1 = cur_N1
        last_N2 = cur_N2
        last_N3 = cur_N3
        last_N4 = cur_N4
        last_Menu = cur_Menu

        time.sleep(LOOP_DELAY)
        continue

    # ================================================================
    #  Normal Mode (Remote Control)
    # ================================================================
    # --- 1. Read joysticks ---
    Lx = gamepad.get_joystick("Lx")
    Ly = gamepad.get_joystick("Ly")
    Rx = gamepad.get_joystick("Rx")

    # --- 2. Read buttons ---
    cur_N1 = gamepad.is_key_pressed("N1")
    cur_N2 = gamepad.is_key_pressed("N2")
    cur_N3 = gamepad.is_key_pressed("N3")
    cur_N4 = gamepad.is_key_pressed("N4")
    cur_Plus = gamepad.is_key_pressed("+")
    cur_Menu = gamepad.is_key_pressed("≡")
    cur_L1 = gamepad.is_key_pressed("L1")
    cur_R1 = gamepad.is_key_pressed("R1")
    cur_L2 = gamepad.is_key_pressed("L2")
    cur_R2 = gamepad.is_key_pressed("R2")
    cur_Dpad_Up = gamepad.is_key_pressed("Up")
    cur_Dpad_Down = gamepad.is_key_pressed("Down")
    cur_Dpad_Left = gamepad.is_key_pressed("Left")
    cur_Dpad_Right = gamepad.is_key_pressed("Right")

    # D-pad 冲突保护：连续 3 次同时按下才拦截（避免单次信号抖动误杀）
    if cur_Dpad_Left and cur_Dpad_Right:
        _dpad_lr_conflict += 1
    else:
        _dpad_lr_conflict = 0
    if _dpad_lr_conflict >= 3:
        cur_Dpad_Left = False
        cur_Dpad_Right = False

    if cur_Dpad_Up and cur_Dpad_Down:
        _dpad_ud_conflict += 1
    else:
        _dpad_ud_conflict = 0
    if _dpad_ud_conflict >= 3:
        cur_Dpad_Up = False
        cur_Dpad_Down = False

    # --- 3. Menu key: toggle debug mode ---
    if cur_Menu and not last_Menu:
        if debug_mode:
            debug_stop_motor()
            debug_mode = False
            stop_all_motors()
            __led.show("Main")
        else:
            debug_mode = True
            debug_motor_type = 0
            debug_motor_index = 0
            __led.show("Test")
            __led.show("M1")
        last_Menu = cur_Menu
        # Reset all edge vars to prevent false triggers
        last_Up = last_Down = last_Left = last_Right = False
        last_N1 = last_N2 = last_N3 = last_N4 = False
        last_R2 = last_L1 = last_R1 = last_L2 = last_Plus = False
        last_Dpad_Up = last_Dpad_Down = last_Dpad_Left = last_Dpad_Right = False
        _dpad_lr_conflict = _dpad_ud_conflict = 0
        time.sleep(0.3)
        continue

    # --- 4. D-pad ←: DC3 振荡 -100↔+100（按一下启动，再按停） ---
    if cur_Dpad_Left and not last_Dpad_Left:
        dc3_osc = not dc3_osc
        if dc3_osc:
            dc3_osc_dir = 1
            dc3_osc_timer = novapi.timer()
            print(">>> D-pad←: DC3 振荡启动")
        else:
            power_expand_board.set_power(DC_COLLECTOR_PORT3, 0)
            print(">>> D-pad←: DC3 停止")
    if dc3_osc and novapi.timer() - dc3_osc_timer >= 0.5:
        dc3_osc_dir = -dc3_osc_dir
        dc3_osc_timer = novapi.timer()
        power_expand_board.set_power(DC_COLLECTOR_PORT3, dc3_osc_dir * 100)

    # D-pad ↑/↓: 无刷电机速度 ±5（范围 10~100）
    if cur_Dpad_Up and not last_Dpad_Up:
        BL_ACTION_SPEED = min(100, BL_ACTION_SPEED + 5)
        if bl1_on:
            power_expand_board.set_power("BL1", BL_ACTION_SPEED)
            power_expand_board.set_power("BL2", BL_ACTION_SPEED)
        print(">>> D-pad↑: 无刷速度 = %d" % BL_ACTION_SPEED)
    if cur_Dpad_Down and not last_Dpad_Down:
        BL_ACTION_SPEED = max(10, BL_ACTION_SPEED - 5)
        if bl1_on:
            power_expand_board.set_power("BL1", BL_ACTION_SPEED)
            power_expand_board.set_power("BL2", BL_ACTION_SPEED)
        print(">>> D-pad↓: 无刷速度 = %d" % BL_ACTION_SPEED)
    # D-pad → 空

    # --- 5. L1: 面翻转（正面↔反面）---
    if cur_L1 and not last_L1:
        face_flipped = not face_flipped
        if face_flipped:
            print(">>> L1: 面翻转 → 反面")
        else:
            print(">>> L1: 面翻转 → 正面")

    # --- 6. R2: 双无刷 BL1+BL2 同时开关 ---
    if cur_R2 and not last_R2:
        bl1_on = not bl1_on
        bl2_on = not bl2_on
        if bl1_on:
            power_expand_board.set_power("BL1", BL_ACTION_SPEED)
            power_expand_board.set_power("BL2", BL_ACTION_SPEED)
            print(">>> R2: 双无刷启动 @%d" % BL_ACTION_SPEED)
        else:
            power_expand_board.stop("BL1")
            power_expand_board.stop("BL2")
            print(">>> R2: 双无刷停止")
    # R1 / L2 无效果

    # --- 7. N-keys ---
    # N1: 双舵机（仅在无刷已启动时有效）
    if cur_N1 and not last_N1:
        if not bl1_on and not bl2_on:
            print(">>> N1: 无刷未启动，舵机锁定")
            __led.show("LOCK")
        elif _HAS_SERVO:
            try:
                __servo_1.move_to(SERVO1_ACTION_ANGLE, SERVO_ACTION_SPEED)
                __servo_2.move_to(SERVO2_ACTION_ANGLE, SERVO_ACTION_SPEED)
            except Exception:
                pass
            sv1_phase = 1; sv1_time = novapi.timer()
            sv2_phase = 1; sv2_time = novapi.timer()
            print(">>> N1: 双舵机触发")

    # N2: M5=-100 + DC2=+100  切换（按一下开，再按关，与N4互斥）
    if cur_N2 and not last_N2:
        n2_on = not n2_on
        if n2_on:
            n4_on = False
            __motor_M5.set_power(-100)
            power_expand_board.set_power(DC_COLLECTOR_PORT2, -100)
            print(">>> N2: M5=-100  DC2=-100  开")
        else:
            __motor_M5.set_power(0)
            power_expand_board.set_power(DC_COLLECTOR_PORT2, 0)
            print(">>> N2: 关")

    # N4: M5=+100 + DC2=-100  切换（按一下开，再按关，与N2互斥）
    if cur_N4 and not last_N4:
        n4_on = not n4_on
        if n4_on:
            n2_on = False
            __motor_M5.set_power(100)
            power_expand_board.set_power(DC_COLLECTOR_PORT2, 100)
            print(">>> N4: M5=+100  DC2=+100  开")
        else:
            __motor_M5.set_power(0)
            power_expand_board.set_power(DC_COLLECTOR_PORT2, 0)
            print(">>> N4: 关")

    # N3: unused

    # --- 8. Servo auto-close (SV1 + SV2, 由 N1 触发) ---

    # Update normal-mode edge variables
    last_N1 = cur_N1
    last_N2 = cur_N2
    last_N3 = cur_N3
    last_N4 = cur_N4
    last_Menu = cur_Menu
    last_L1 = cur_L1
    last_R1 = cur_R1
    last_L2 = cur_L2
    last_R2 = cur_R2
    last_Dpad_Up = cur_Dpad_Up
    last_Dpad_Down = cur_Dpad_Down
    last_Dpad_Left = cur_Dpad_Left
    last_Dpad_Right = cur_Dpad_Right

    # --- 10. Servo auto-close (SV1) ---
    if sv1_phase == 1 and novapi.timer() - sv1_time >= SERVO_RETURN_DELAY:
        if _HAS_SERVO:
            try:
                __servo_1.move_to(0, SERVO_ACTION_SPEED)
            except Exception:
                pass
        sv1_phase = 0

    # --- 11. Servo auto-close (SV2) ---
    if sv2_phase == 1 and novapi.timer() - sv2_time >= SERVO_RETURN_DELAY:
        if _HAS_SERVO:
            try:
                __servo_2.move_to(0, SERVO_ACTION_SPEED)
            except Exception:
                pass
        sv2_phase = 0

    # --- 12. + key: start auto program ---
    if cur_Plus and not last_Plus:
        auto_mode = True
        auto_step = 0
        auto_step_start = novapi.timer()
        auto_prev_Vx = 0.0
        auto_prev_Vy = 0.0
        auto_prev_omega = 0.0
        # Clear old calibration data
        _debug_cal_done = False
        _enc_cal_auto_started = False
        _enc_step_initialized = -1
        _cal_delta_M1 = _cal_delta_M2 = _cal_delta_M3 = _cal_delta_M4 = None
        # Print first step info
        first = AUTO_SEQUENCE[0]
        if isinstance(first[0], str):
            print(">>> 自动程序启动！步骤 1/%d: %s" %
                  (len(AUTO_SEQUENCE), first[0]))
        else:
            d0, Vx0, Vy0, w0 = first
            print(">>> 自动程序启动！步骤 1/%d: Vx=%d Vy=%d w=%d (%.1fs)" %
                  (len(AUTO_SEQUENCE), Vx0, Vy0, w0, d0))
    last_Plus = cur_Plus

    # --- 13. Dead zone + response curve + speed scaling ---
    Lx = apply_dead_zone(Lx)
    Ly = apply_dead_zone(Ly)
    Rx = apply_dead_zone(Rx)

    # WPILib 风格指数曲线: 低速细腻、高速爆发
    Lx = apply_response_curve(Lx, JOYSTICK_EXPO)
    Ly = apply_response_curve(Ly, JOYSTICK_EXPO)
    Rx = apply_response_curve(Rx, OMEGA_EXPO)

    Vx = Lx * SPEED_SCALE
    Vy = Ly * SPEED_SCALE
    omega = Rx * SPEED_SCALE

    # --- 14. Direction calibration ---
    if INVERT_VX:
        Vx = -Vx
    if INVERT_VY:
        Vy = -Vy
    if INVERT_OMEGA:
        omega = -omega

    # --- 14b. Face flip: 反面时前后左右全部取反 ---
    if face_flipped:
        Vx = -Vx
        Vy = -Vy

    # --- 15. Kinematics ---
    M1_power, M2_power, M3_power, M4_power = mecanum_kinematics(Vx, Vy, omega)

    # --- 16. Output to chassis motors ---
    __motor_M1.set_power(M1_power)
    __motor_M2.set_power(M2_power)
    __motor_M3.set_power(M3_power)
    __motor_M4.set_power(M4_power)

    # --- 17. LED display ---
    __led.show("S%d" % BL_ACTION_SPEED)

    # --- 18. Loop delay ---
    time.sleep(LOOP_DELAY)
